### Prueba funcionando
GET http://localhost:8003/

### Listar incapacidades
GET http://localhost:8003/incapacidades

### Obtener incapacidad por ID
GET http://localhost:8003/incapacidades/1

### Crear incapacidad
POST http://localhost:8003/incapacidades
Content-Type: application/json

{
    "empleado_id": 1,
    "fecha_inicio": "2026-06-10",
    "fecha_fin": "2026-06-15",
    "tipo": "enfermedad_general",
    "diagnostico_general": "Gripe fuerte",
    "entidad_medica": "Clinica del Norte",
    "observaciones": "Reposo totall"
}

### Actualizar incapacidad
PUT http://localhost:8003/incapacidades/3
Content-Type: application/json

{
    "observaciones": "Reposo total y medicamento"
}

### Cambiar estado
PATCH http://localhost:8003/incapacidades/1/estado
Content-Type: application/json

{
    "estado": "en_revision"
}

### Finalizar incapacidad
PATCH http://localhost:8003/incapacidades/1/finalizar

### Buscar por empleado
GET http://localhost:8003/incapacidades/buscar?empleado_id=1

### Buscar por estado 
GET http://localhost:8003/incapacidades/buscar?estado=en_revision

### Buscar por tipo
GET http://localhost:8003/incapacidades/buscar?tipo=licencia_medica